# Generated by Django 6.0.3 on 2026-03-04 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='用户问题')),
                ('answer', models.TextField(verbose_name='AI回答')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='对话时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提问用户')),
            ],
            options={
                'db_table': 'scanner_ai_chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：公司官网', max_length=100, verbose_name='资产名称')),
                ('target', models.CharField(help_text='IP地址或URL', max_length=255, verbose_name='目标地址')),
                ('asset_type', models.CharField(choices=[('web', 'Web应用'), ('host', '主机/服务器')], max_length=20, verbose_name='资产类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'db_table': 'scanner_asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('web_vuln', 'Web漏洞扫描'), ('port_service', '端口与服务扫描')], max_length=50, verbose_name='扫描类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '扫描中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='任务状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.asset', verbose_name='目标资产')),
            ],
            options={
                'db_table': 'scanner_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_name', models.CharField(max_length=255, verbose_name='漏洞名称')),
                ('severity', models.CharField(choices=[('critical', '严重'), ('high', '高危'), ('medium', '中危'), ('low', '低危'), ('info', '信息')], max_length=20, verbose_name='危险等级')),
                ('description', models.TextField(blank=True, null=True, verbose_name='漏洞描述')),
                ('remediation', models.TextField(blank=True, null=True, verbose_name='修复建议')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, verbose_name='发现时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.scantask', verbose_name='所属扫描任务')),
            ],
            options={
                'db_table': 'scanner_vulnerability',
                'ordering': ['-discovered_at'],
            },
        ),
    ]
