# Generated by Django 6.0.3 on 2026-03-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_alter_vulnerability_extracted_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='os_type',
            field=models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='系统类型'),
        ),
    ]
